name: CI Workflow

on:
  push
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./Challenge-1
      run: npm install

    - name: Run tests
      working-directory: ./Challenge-1
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./Challenge-1/coverage.xml
        fail_ci_if_error: true
        flags: unittests
        token: c7c46815-df5e-4bcc-bd0f-8b40c03aff8e
        
