name: "Test outputs on commit"
on:
  pull_request:
  push:
    branches:
      - main

jobs:

  tests:
    name: "TestsOnCommits"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
    
      - name: Install Forta dependencies
        working-directory: ./Challenge-2
        shell: bash
        run: npm install
    
      - name: Run tests
        working-directory: ./Challenge-2
        shell: bash
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
         
          

